server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ayoubCenter
    username: root
    password: root
  application:
    name: ayoubCenter
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
