version: '3.1'

services:
  sportscenter-mysql:
    image: mysql
    restart: always
    container_name: "ayoubCenter-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: '@youbm@hjouby'
    ports:
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - ayoubCenter-mysql-data:/var/lib/mysql

  sportscenter-redis:
    image: "redis:latest"
    container_name: "ayoubCenter-redis-container"
    ports:
      - "6379:6379"
    volumes:
      - ayoubCenter-redis-data:/data

volumes:
  ayoubCenter-redis-data:
  ayoubCenter-mysql-data: